// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsoetsrhittfkijucoot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzb2V0c3JoaXR0ZmtpanVjb290Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzkzNTMsImV4cCI6MjA3MDgxNTM1M30.xLSoSF7_XupOKzqxY-cfkAI8hqVebDFP6L69UZfp6xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});